- id: '1575102185394'
  alias: Wake up
  description: ''
  trigger:
  - at: '8:00'
    platform: time
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - data:
      entity_id:
      - light.bedroom
    service: light.turn_on
  - alias: ''
    data:
      message: Good morning Lucas!
    entity_id:
      - media_player.bedroom
      - media_player.living_room
    service: tts.google_translate_say
- id: '1575102185394'
  alias: Standup
  description: ''
  trigger:
  - at: '10:15'
    platform: time
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - alias: ''
    data:
      message: Time for standup
    entity_id:
      - media_player.living_room
    service: tts.google_translate_say
- id: '1575104738252'
  alias: Coming home
  description: ''
  trigger:
  - entity_id: person.lucas_kjaero_zhang
    platform: state
    to: home
  - entity_id: person.luqi_kjaero_zhang
    platform: state
    to: home
  condition: []
  action:
  - device_id: c0b36a04dd62460983505fe8f7bfd60f
    domain: light
    entity_id: light.elephant_lamp
    type: turn_on
  - data:
      message: Welcome home
    entity_id:
      - media_player.living_room
    service: tts.google_translate_say
- id: '1575102185395'
  alias: Time to start work
  description: ''
  trigger:
  - at: '9:00'
    platform: time
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - alias: ''
    data:
      message: Time to start work
    entity_id:
      - media_player.bedroom
      - media_player.living_room
    service: tts.google_translate_say
- id: '1575102185396'
  alias: Time to stop work
  description: ''
  trigger:
  - at: '17:00'
    platform: time
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - alias: ''
    data:
      message: Time to stop work
    entity_id:
      - media_player.bedroom
      - media_player.living_room
    service: tts.google_translate_say
