- id: '1575095448607'
  alias: Go to sleep fan
  description: ''
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      message: Go to sleep fan
    entity_id: all
    service: tts.google_translate_say
- id: '1575102185394'
  alias: Wake up
  description: ''
  trigger:
  - at: '7:30'
    platform: time
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - data:
      entity_id:
      - light.bedroom
    service: light.turn_on
  - alias: ''
    data:
      message: Good morning Lucas
    entity_id:
      - media_player.bedroom
      - media_player.living_room
    service: tts.google_translate_say
