name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install home assistant
      run: |
       apt-get install python3-setuptools
       python3 -m pip install homeassistant
    - name: Set up dummy secrets file
      run: mv secrets-build.yaml secrets.yaml
    - name: Test configuration
      run: hass --script check_config -c .
